---
title: "Copynumber PCAs - ANOVA"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/rpianezza/TE/')
```

```{r}
library(tidyverse)
library(ggpubr)
HGDP <- read_delim("/Volumes/Temp1/rpianezza/TE/summary-HGDP/USEME_HGDP_complete_reflib6.2_mq10_batchinfo_cutoff0.01.txt")
names(HGDP) <- c("ID","pop","sex","country","type","familyname","length","reads","copynumber","batch")

SGDP <- read_tsv("/Volumes/Temp2/rpianezza/SGDP/summary/USEME_SGDP_cutoff") %>% dplyr::rename(ID=biosample)

HGDP_pcr_free_samples <- read_tsv("/Volumes/Temp1/rpianezza/investigation/HGDP-no-PCR/HGDP-only-pcr-free-samples.tsv", col_names = "ID")
HGDP_pcr_free <- HGDP %>% filter(ID %in% HGDP_pcr_free_samples$ID)
HGDP_pcr <- HGDP %>% filter(!(ID %in% HGDP_pcr_free_samples$ID))

SGDP_pcr_free_samples <- read_tsv("/Volumes/Temp1/rpianezza/SGDP/ric-documentation/SGDP-no-PCR.tsv")
SGDP_pcr_free <- SGDP %>% filter(ID %in% SGDP_pcr_free_samples$ID)

HvariableTEs <- filter(HGDP_pcr_free, type == "te") %>% group_by(familyname) %>% summarise(variance = var(copynumber)) %>% filter(variance>0.5) %>% select(familyname) %>% pull()
```

# Function for PCA + ANOVA test

```{r}
ANOVA_PCA_copynumber <- function(raw_data, title){
data <- filter(raw_data, type=="te")
m <- filter(data, sex=='male')
f <- filter(data, sex=='female')
len <- length(unique(data$familyname))
males <- length(unique(m$ID))
females <- length(unique(f$ID))

f_matrix <- matrix(as.vector(f$copynumber),nrow=females,ncol=len,byrow=T)
f_fram <- data.frame(f_matrix)
names(f_fram) <- unique(f$familyname)
f_fram <- f_fram %>% select_if(negate(function(col) sd(col)==0))
f_matrixcont <- matrix(as.vector(f$country),nrow=females,ncol=len,byrow=T)
f_framcont <- data.frame(f_matrixcont)
f_contcol<-c(f_framcont$X1)

m_matrix <- matrix(as.vector(m$copynumber),nrow=males,ncol=len,byrow=T)
m_fram <- data.frame(m_matrix)
names(m_fram)<-unique(m$familyname)
m_fram <- m_fram %>% select_if(negate(function(col) sd(col)==0))
m_matrixcont <- matrix(as.vector(m$country),nrow=males,ncol=len,byrow=T)
m_framcont <- data.frame(m_matrixcont)
m_contcol<-c(m_framcont$X1)

fHGDP.pca <- prcomp(f_fram, center = TRUE, scale = TRUE)
mHGDP.pca <- prcomp(m_fram, center = TRUE, scale = TRUE)

# Create an empty tibble to store the results
results <- tibble()

# Perform ANOVA on PC1 and PC2 for the female samples
for (i in c(1:10)) {
  model <- aov(fHGDP.pca$x[,i] ~ f_contcol)
  summary_res <- summary(model)
  
  # Extract the F value and p-value from the summary and the explained variability
  f_value <- summary_res[[1]]$F[1]
  p_value <- summary_res[[1]]$`Pr(>F)`[1]
  explained_var <- (fHGDP.pca$sdev[i]^2/sum(fHGDP.pca$sdev^2))*100
  
  if (p_value < 0.001) {
significance <- "strong"
} else if (p_value >= 0.001 & p_value < 0.01) {
significance <- "moderate"
} else if (p_value >= 0.01 & p_value < 0.05) {
significance <- "weak"
} else if (p_value >= 0.05 & p_value < 0.1) {
significance <- "little"
} else {
significance <- "no-evidence"
}
  
  # Store the results in the tibble
  results <- results %>% bind_rows(tibble(PC = paste0("PC", i), Sex = "Female", F = f_value, p = p_value, Explained_Variability = explained_var, Significance = significance))
}

# Repeat the ANOVA analysis for the male samples
for (i in c(1:10)) {
  model <- aov(mHGDP.pca$x[,i] ~ m_contcol)
  summary_res <- summary(model)
  
  # Extract the F value and p-value from the summary and the explained variability
  f_value <- summary_res[[1]]$F[1]
  p_value <- summary_res[[1]]$`Pr(>F)`[1]
  explained_var <- (mHGDP.pca$sdev[i]^2/sum(mHGDP.pca$sdev^2))*100
  
  if (p_value < 0.001) {
significance <- "strong"
} else if (p_value >= 0.001 & p_value < 0.01) {
significance <- "moderate"
} else if (p_value >= 0.01 & p_value < 0.05) {
significance <- "weak"
} else if (p_value >= 0.05 & p_value < 0.1) {
significance <- "little"
} else {
significance <- "no-evidence"
}
  
  # Store the results in the tibble
  results <- results %>% bind_rows(tibble(PC = paste0("PC", i), Sex = "Male", F = f_value, p = p_value, Explained_Variability = explained_var, Significance = significance))
}

# Print the results
print(results)
}
```


# PCA

PCA excluding biased samples (PCR samples + GC biased samples PCR free) and excluding non-variable TEs.

## HGDP

```{r}
a_HGDP <- read_tsv("/Volumes/Temp1/rpianezza/PCA-copynumber-all-analysis/a_HGDP.tsv")
HGDP_nobiased_samples <- filter(a_HGDP, (a > (-0.5)) & (a<0.5)) %>% select(ID) %>% pull()
HGDP_nobiasedID <- filter(HGDP, ID %in% HGDP_nobiased_samples)
HGDP_nobiasedID_pcrfree <- filter(HGDP_pcr_free, ID %in% HGDP_nobiased_samples)
HGDP_nobiasedID_pcrfree_varTE <- filter(HGDP_nobiasedID_pcrfree, familyname %in% HvariableTEs)

ANOVA_PCA_copynumber(HGDP_nobiasedID_pcrfree_varTE, "HGDP - GC biased samples excluded - Variable TEs")
```


## SGDP

```{r}
SvariableTEs <- filter(SGDP_pcr_free, type == "te") %>% group_by(familyname) %>% summarise(variance = var(copynumber)) %>% filter(variance>0.5) %>% select(familyname) %>% pull()

a_SGDP <- read_tsv("/Volumes/Temp1/rpianezza/PCA-copynumber-all-analysis/a_SGDP.tsv")
SGDP_nobiased_samples <- filter(a_SGDP, (a > (-0.5)) & (a<0.5)) %>% select(ID) %>% pull()
SGDP_nobiasedID <- filter(SGDP, ID %in% SGDP_nobiased_samples)
SGDP_nobiasedID_pcrfree <- filter(SGDP_pcr_free, ID %in% SGDP_nobiased_samples)
SGDP_nobiasedID_pcrfree_varTE <- filter(SGDP_nobiasedID_pcrfree, familyname %in% SvariableTEs)

ANOVA_PCA_copynumber(SGDP_nobiasedID_pcrfree_varTE, "SGDP - GC biased samples excluded - Variable TEs")
```

## Test different PCs for SGDP based on the ANOVA test results

```{r}
PCA_copynumber <- function(raw_data, title, colors){
  
color_palette <- colors
    
data <- filter(raw_data, type=="te")
m <- filter(data, sex=='male')
f <- filter(data, sex=='female')
len <- length(unique(data$familyname))
males <- length(unique(m$ID))
females <- length(unique(f$ID))

f_matrix <- matrix(as.vector(f$copynumber),nrow=females,ncol=len,byrow=T)
f_fram <- data.frame(f_matrix)
names(f_fram) <- unique(f$familyname)
f_fram <- f_fram %>% select_if(negate(function(col) sd(col)==0))
f_matrixcont <- matrix(as.vector(f$country),nrow=females,ncol=len,byrow=T)
f_framcont <- data.frame(f_matrixcont)
f_contcol<-c(f_framcont$X1)

m_matrix <- matrix(as.vector(m$copynumber),nrow=males,ncol=len,byrow=T)
m_fram <- data.frame(m_matrix)
names(m_fram)<-unique(m$familyname)
m_fram <- m_fram %>% select_if(negate(function(col) sd(col)==0))
m_matrixcont <- matrix(as.vector(m$country),nrow=males,ncol=len,byrow=T)
m_framcont <- data.frame(m_matrixcont)
m_contcol<-c(m_framcont$X1)
  
fHGDP.pca <- prcomp(f_fram, center = TRUE, scale = TRUE)
f_var <- summary(fHGDP.pca)$importance[2,1]

fHGDP.pca <- prcomp(f_fram, center = TRUE, scale = TRUE)
f_var1 <- summary(fHGDP.pca)$importance[2,5]
f_var2 <- summary(fHGDP.pca)$importance[2,7]

f_PCA <- ggplot(data=f_fram, aes(x=fHGDP.pca$x[,5], y=fHGDP.pca$x[,7], color = f_contcol)) + 
geom_point() + 
ggtitle("Females") + 
xlab(paste0("PC5 (", round(f_var1,3)*100,"%)")) + 
ylab(paste0("PC7 (",round(f_var2,3)*100,"%)")) + 
theme(plot.title = element_text(size = 8, hjust = 0.5))+ 
guides(col = guide_colourbar(title = ""))+ 
scale_color_manual(values = color_palette)

mHGDP.pca <- prcomp(m_fram, center = TRUE, scale = TRUE)
m_var1 <- summary(mHGDP.pca)$importance[2,5]
m_var2 <- summary(mHGDP.pca)$importance[2,6]

m_PCA <- ggplot(data=m_fram, aes(x=mHGDP.pca$x[,5], y=mHGDP.pca$x[,6], color = m_contcol)) +
geom_point() +
ggtitle("Males") +
xlab(paste0("PC5 (", round(m_var1,3)*100,"%)")) +
ylab(paste0("PC6 (",round(m_var2,3)*100,"%)")) +
theme(plot.title = element_text(size = 8, hjust = 0.5))+ 
scale_color_manual(values = color_palette)

figure <- ggarrange(f_PCA, m_PCA, ncol = 2, nrow = 1, common.legend = TRUE, legend = "bottom", font.label = list(size = 10, color = "black", face = "bold", family = NULL, position = "top"))
annotate_figure(figure, top = text_grob(title, color = "black", size = 20), fig.lab = "")
}

SGDP_colors <- c("Africa" = "#F8766D", "America" = "#C49A00", "Central Asia and Siberia" = "#53B400", "East Asia" = "#00C094", "West Eurasia" = "#00B6EB", "South Asia" = "#A58AFF", "Oceania" = "#FB61D7")

PCA_copynumber(SGDP_nobiasedID_pcrfree_varTE, "SGDP - GC biased samples excluded - Variable TEs", SGDP_colors)
```
