---
title: "UMAP - HGDP - SNPs - SCGs"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

## Prepare the environment

```{r env}
library(tidyverse)
library(ggpubr)
library(umap)
```

## Select samples with no GC-bias

```{r samples selection}
HGDP <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv")
```

## Read the SNPs matrixes

The SNPs matrixes are created using the script **frequency_matrix.py**.

```{r SNP-matrixes}
kSNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/NA/scg-cov15-1000SNPs.matrix.tsv"
k10SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/NA/scg-cov15-10000SNPs.matrix.tsv"
k100SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/NA/scgs-cov15-100000SNPs.matrix.tsv"
```

## Create the function for UMAP plotting

```{r main-function}
UMAP <- function(freq_matrix, metadata, titlee){

matrix <- read_csv(freq_matrix)
metadata <- metadata %>% select(ID, sex, country, pop) %>% distinct()
matrix <- inner_join(metadata, matrix, by="ID")

pca_data <- matrix %>% select_if(~ !all(. == .[1]))
matrix <- as.matrix(pca_data[, -c(1,2,3,4)])

umap_result <- umap(matrix, n_neighbors = 15, min_dist = 0.3)

umap <- umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")

plot <- umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = metadata$country))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", title = titlee, color = "Region") + theme(plot.title = element_text(hjust = 0.5, face = "bold"), legend.title = element_text(face = "bold"))
}
```

```{r}
(UMAP_1kSNPs <- UMAP(kSNPs, HGDP, "HGDP - SCGs - 1.000 SNPs"))
(UMAP_10kSNPs <- UMAP(k10SNPs, HGDP, "HGDP - SCGs - 10.000 SNPs"))
#(UMAP_100kSNPs <- UMAP(k100SNPs, HGDP, "HGDP - SCGs - 100.000 SNPs"))
```
