---
title: "UMAP - SNPs - HGDP - Select variants specific for each copynumber bin"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

## Prepare the environment

```{r env}
library(tidyverse)
library(ggpubr)
library(umap)
```

## Select samples

```{r samples selection}
HGDP <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv")

HGDP_f <- HGDP %>% filter(sex=="female")
HGDP_m <- HGDP %>% filter(sex=="male")

HGDP_pcr_free_samples <- read_tsv("/Volumes/Temp1/rpianezza/investigation/HGDP-no-PCR/HGDP-only-pcr-free-samples.tsv", col_names = "ID")

HGDP_pcr_free <- HGDP %>% filter(ID %in% HGDP_pcr_free_samples$ID)

a_HGDP <- read_tsv("/Volumes/Temp1/rpianezza/PCA-copynumber-all-analysis/a_HGDP.tsv")
HGDP_nobiased_samples <- filter(a_HGDP, (a > (-0.5)) & (a<0.5)) %>% select(ID) %>% pull()
HGDP_nobiasedID <- filter(HGDP, ID %in% HGDP_nobiased_samples)
(HGDP_clean <- filter(HGDP_pcr_free, ID %in% HGDP_nobiased_samples, type=="te"))
```

## Read the SNPs matrixes

The SNPs matrixes are created using the script **frequency_matrix_v7.py**. This version of the script filters automatically the non-variable TEs in copynumber.

```{r bin-copynumbers}
bins <- HGDP_clean %>% group_by(familyname) %>% summarise(mean = mean(copynumber)) %>% mutate(class = case_when(
    mean < 10 ~ "low",
    mean > 10 & mean < 100 ~ "mid",
    mean > 100 ~ "high"
  ))

classification <- read_tsv("/Volumes/Temp1/rpianezza/GC-content/repbase_full_classification.txt") %>% select(-class) %>% inner_join(bins, by="familyname") %>% select(-mean)

#write_tsv(classification, "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/copynumber-bins/classification_copynumber_bins")
```


```{r SNP-matrixes}
females <- ""
males <- ""
together_high <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/copynumber-bins/high-10k"
together_mid <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/copynumber-bins/mid-10k"
together_low <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/copynumber-bins/low-10k"
```

## Create the function for UMAP plotting

```{r split-function}
UMAP_split <- function(freq_matrix, metadata, titlee){

matrix <- read_csv(freq_matrix)
  
f_metadata <- metadata %>% filter(sex=="female") %>% select(ID, sex, country, pop) %>% distinct()
m_metadata <- metadata %>% filter(sex=="male") %>% select(ID, sex, country, pop) %>% distinct()
males_matrix <- inner_join(m_metadata, matrix, by="ID")
females_matrix <- inner_join(f_metadata, matrix, by="ID")

f_pca_data <- females_matrix %>% select_if(~ !all(. == .[1]))
m_pca_data <- males_matrix %>% select_if(~ !all(. == .[1]))
f_matrix <- as.matrix(f_pca_data[, -c(1,2,3)])
m_matrix <- as.matrix(m_pca_data[, -c(1,2,3)])

f_umap_result <- umap(f_matrix, n_neighbors = 15, min_dist = 0.3)
m_umap_result <- umap(m_matrix, n_neighbors = 15, min_dist = 0.3)

f_umap <- f_umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")
m_umap <- m_umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")

f <- f_umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = f_metadata$country))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", subtitle = "Females", color = "Region") + theme(plot.subtitle = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))

m <- m_umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = m_metadata$country))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", subtitle = "Males", color = "Region") + theme(plot.subtitle = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))

plot <- ggarrange(f, m, ncol = 2, nrow = 1, common.legend = TRUE, legend = "bottom", align = "hv", font.label = list(size = 10, color = "black", face = "bold", family = NULL, position = "top"))
figure <- annotate_figure(plot, top = text_grob(titlee, face = "bold", size = 14))
}
```

```{r joined-function}
UMAP <- function(freq_matrix, metadata, sex, titlee){

matrix <- read_csv(freq_matrix)
metadata <- metadata %>% select(ID, sex, country, pop) %>% distinct()
matrix <- inner_join(metadata, matrix, by="ID")

pca_data <- matrix %>% select_if(~ !all(. == .[1]))
matrix <- as.matrix(pca_data[, -c(1,2,3,4)])

umap_result <- umap(matrix, n_neighbors = 15, min_dist = 0.3)
umap <- umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")

plot <- umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = metadata$country, shape = metadata$sex))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", title = titlee, subtitle = sex, color = "Region", shape = "Sex") + theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.subtitle = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))
}
```

```{r}
(UMAP_high_split <- UMAP_split(together_high, HGDP, "HGDP - 10.000 SNPs in RepSeq"))
(UMAP_high <- UMAP(together_high, HGDP, "Males and females", "HGDP - 10.000 SNPs in RepSeq"))
```

```{r}
(UMAP_mid_split <- UMAP_split(together_mid, HGDP, "HGDP - 10.000 SNPs in RepSeq"))
(UMAP_mid <- UMAP(together_mid, HGDP, "Males and females", "HGDP - 10.000 SNPs in RepSeq"))
```

```{r}
(UMAP_low_split <- UMAP_split(together_low, HGDP, "HGDP - 10.000 SNPs in RepSeq"))
(UMAP_low <- UMAP(together_low, HGDP, "Males and females", "HGDP - 10.000 SNPs in RepSeq"))
```

