---
title: "HGDP - GC bias normalization"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/rpianezza/TE/')
```


```{r}
library(tidyverse)
library(ggpubr)

theme_set(theme_bw())

HGDP <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv")

#a_HGDP <- read_tsv("/Volumes/Temp1/rpianezza/PCA-copynumber-all-analysis/a_HGDP.tsv")
#HGDP_nobiased_samples <- filter(a_HGDP, (a > (-0.5)) & (a<0.5)) %>% select(ID) %>% pull()
#HGDP_clean <- filter(HGDP, ID %in% HGDP_nobiased_samples)

DNA_names <- c("Crypton", "hAT", "Helitron", "Kolobok", "Mariner/Tc1", "Merlin", "MuDR", "piggyBac", "DNA transposon")
LINE_names <- c("L1", "CR1", "L2", "Crack", "RTE", "RTEX", "R4", "Vingi", "Tx1", "Penelope")
SINE_names <- c("SINE1/7SL", "SINE2/tRNA", "SINE3/5S", "SINE")
LTR_names <- c("ERV1", "ERV2", "ERV3", "Gypsy", "Endogenous Retrovirus", "LTR Retrotransposon", "Long terminal repeat", "Non-LTR Retrotransposon")
satellites_names <- c("Satellite", "satellite", "SAT")

classification <- HGDP %>% mutate(class = case_when(superfamily %in% DNA_names ~ "DNA", superfamily %in% LINE_names ~ "LINE", superfamily %in% SINE_names ~ "SINE", superfamily %in% LTR_names ~ "LTR", superfamily %in% satellites_names ~ "satellite"))

coordinates <- read_tsv("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_populationcoordinates.txt", col_names = c("pop", "country", "lat", "long")) %>% select(-country)
(full <- inner_join(classification, coordinates, by="pop") %>% filter(type=="te") %>% select(-type, -batch))
```

```{r}
gc_content <- read_tsv("/Volumes/Temp1/rpianezza/GC-content/gc-content.tsv")

scg_gc <- gc_content %>% filter(type=="scg") %>% select(-type, -length)
cov_scg <- HGDP %>% filter(type=="scg") %>% select(ID, familyname, copynumber)
(scg_gc_table <- inner_join(scg_gc, cov_scg, by="familyname"))

te_gc <- gc_content %>% filter(type=="te") %>% select(-type, -length)
cov_te <- HGDP %>% filter(type=="te") %>% select(ID, familyname, copynumber)
(te_gc_table <- inner_join(te_gc, cov_te, by="familyname"))
```

```{r}
fitting <- function(gc_data){
    fit <- lm(copynumber ~ poly(GC_content, 2, raw = TRUE), data = gc_data)
    coefficients <- coef(fit)
  return(coefficients)
}

corrected_dataset <- tibble(
  ID = character(),
  familyname = character(),
  GC_content = numeric(),
  expected_1_copy = numeric(),
  copynumber = numeric(),
  gc_copynumber = numeric(),
  gc_coefficients = character()
)

IDs <- HGDP %>% select(ID) %>% distinct() %>% pull()

for (id in IDs){
  gc_table <- scg_gc_table %>% filter(ID == id)
  coefficients <- fitting(gc_table)
  a <- coefficients[1]
  b <- coefficients[2]
  c <- coefficients[3]

te_table <- te_gc_table %>% filter(ID == id)
normalized_copynumbers <- te_table %>%
mutate(expected_1_copy = a+(b*GC_content)+c*(GC_content*GC_content), diff_from_1 = 1-expected_1_copy, gc_copynumber = round((copynumber+(diff_from_1*copynumber)),2)) %>% mutate(gc_coefficients = paste0(round((a),3), ":", round((b),3), ":", round((c),3)))

corrected_dataset <- bind_rows(corrected_dataset, normalized_copynumbers)
}

corrected_dataset_clean <- corrected_dataset %>% select(-copynumber)
corrected_dataset_clean

#ggplot(gc_table, aes(x = gc, y = copynumber)) +
  #geom_point() +
  #geom_smooth(method = "lm", color="grey", se=T, formula = y~poly(x,2)) +
  #xlab("gc") + ylab("copynumber")
```

```{r}
(final_dataset <- inner_join(full, corrected_dataset_clean, by = c("ID", "familyname")))

write_tsv(final_dataset, "/Volumes/Temp1/rpianezza/GC-content/HGDP-final-dataset.tsv")
```
