---
title: "UMAP - SNPs - HGDP - Different TE classes"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

## Prepare the environment

```{r env}
library(tidyverse)
library(ggpubr)
library(umap)
```

## Select samples with no GC-bias

```{r samples selection}
HGDP <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv")
```

## Read the SNPs matrixes

```{r SNP-matrixes}
NC_kSNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/NC-cov15-1000SNPs.matrix.tsv"
NC_k10SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/NC-cov15-10000SNPs.matrix.tsv"

DNA_kSNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/DNA-cov15-1000SNPs.matrix.tsv"
DNA_k10SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/DNA-cov15-10000SNPs.matrix.tsv"

LINE_kSNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/LINE-cov15-1000SNPs.matrix.tsv"
LINE_k10SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/LINE-cov15-10000SNPs.matrix.tsv"

SINE_kSNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/SINE-cov15-1000SNPs.matrix.tsv"
SINE_k10SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/SINE-cov15-10000SNPs.matrix.tsv"

LTR_kSNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/LTR-cov15-1000SNPs.matrix.tsv"
LTR_k10SNPs <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/matrixes/classes/LTR-cov15-10000SNPs.matrix.tsv"
```

## Create the function for UMAP plotting

```{r split-function}
UMAP_split <- function(freq_matrix, metadata, titlee){

matrix <- read_csv(freq_matrix)
  
f_metadata <- metadata %>% filter(sex=="female") %>% select(ID, sex, country, pop) %>% distinct()
m_metadata <- metadata %>% filter(sex=="male") %>% select(ID, sex, country, pop) %>% distinct()
males_matrix <- inner_join(m_metadata, matrix, by="ID")
females_matrix <- inner_join(f_metadata, matrix, by="ID")

f_pca_data <- females_matrix %>% select_if(~ !all(. == .[1]))
m_pca_data <- males_matrix %>% select_if(~ !all(. == .[1]))
f_matrix <- as.matrix(f_pca_data[, -c(1,2,3)])
m_matrix <- as.matrix(m_pca_data[, -c(1,2,3)])

f_umap_result <- umap(f_matrix, n_neighbors = 15, min_dist = 0.3)
m_umap_result <- umap(m_matrix, n_neighbors = 15, min_dist = 0.3)

f_umap <- f_umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")
m_umap <- m_umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")

f <- f_umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = f_metadata$country))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", subtitle = "Females", color = "Region") + theme(plot.subtitle = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))

m <- m_umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = m_metadata$country))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", subtitle = "Males", color = "Region") + theme(plot.subtitle = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))

plot <- ggarrange(f, m, ncol = 2, nrow = 1, common.legend = TRUE, legend = "bottom", align = "hv", font.label = list(size = 10, color = "black", face = "bold", family = NULL, position = "top"))
figure <- annotate_figure(plot, top = text_grob(titlee, face = "bold", size = 14))
}
```

```{r joined-function}
UMAP <- function(freq_matrix, metadata, titlee){

matrix <- read_csv(freq_matrix)
metadata <- metadata %>% select(ID, sex, country, pop) %>% distinct()
matrix <- inner_join(metadata, matrix, by="ID")

pca_data <- matrix %>% select_if(~ !all(. == .[1]))
matrix <- as.matrix(pca_data[, -c(1,2,3,4)])

umap_result <- umap(matrix, n_neighbors = 15, min_dist = 0.3)
umap <- umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")

plot <- umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = metadata$country, shape = metadata$sex))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", title = titlee, subtitle = "Females and males", color = "Region", shape = "Sex") + theme(plot.title = element_text(hjust = 0.5, face = "bold"), plot.subtitle = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))
}
```

```{r NC}
(UMAP_NC_1k_split <- UMAP_split(NC_kSNPs, HGDP, "HGDP - 1.000 SNPs in Non-Classified RepSeq"))
(UMAP_NC_1k <- UMAP(NC_kSNPs, HGDP, "HGDP - 1.000 SNPs in Non-Classified RepSeq"))

(UMAP_NC_10k_split <- UMAP_split(NC_k10SNPs, HGDP, "HGDP - 10.000 SNPs in Non-Classified RepSeq"))
(UMAP_NC_10k <- UMAP(NC_k10SNPs, HGDP, "HGDP - 10.000 SNPs in Non-Classified RepSeq"))
```

```{r DNA}
(UMAP_DNA_1k_split <- UMAP_split(DNA_kSNPs, HGDP, "HGDP - 1.000 SNPs in DNA TEs"))
(UMAP_DNA_1k <- UMAP(DNA_kSNPs, HGDP, "HGDP - 1.000 SNPs in DNA TE"))

(UMAP_DNA_10k_split <- UMAP_split(DNA_k10SNPs, HGDP, "HGDP - 10.000 SNPs in DNA TEs"))
(UMAP_DNA_10k <- UMAP(DNA_k10SNPs, HGDP, "HGDP - 10.000 SNPs in DNA TE"))
```

```{r LINE}
(UMAP_LINE_1k_split <- UMAP_split(LINE_kSNPs, HGDP, "HGDP - 1.000 SNPs in LINE TEs"))
(UMAP_LINE_1k <- UMAP(LINE_kSNPs, HGDP, "HGDP - 1.000 SNPs in LINE TEs"))

(UMAP_LINE_10k_split <- UMAP_split(LINE_k10SNPs, HGDP, "HGDP - 10.000 SNPs in LINE TEs"))
(UMAP_LINE_10k <- UMAP(LINE_k10SNPs, HGDP, "HGDP - 10.000 SNPs in LINE TEs"))
```

```{r SINE}
(UMAP_SINE_1k_split <- UMAP_split(SINE_kSNPs, HGDP, "HGDP - 1.000 SNPs in SINE TEs"))
(UMAP_SINE_1k <- UMAP(SINE_kSNPs, HGDP, "HGDP - 1.000 SNPs in SINE TEs"))

(UMAP_SINE_10k_split <- UMAP_split(SINE_k10SNPs, HGDP, "HGDP - 10.000 SNPs in SINE TEs"))
(UMAP_SINE_10k <- UMAP(SINE_k10SNPs, HGDP, "HGDP - 10.000 SNPs in SINE TEs"))
```

```{r LTR}
(UMAP_LTR_1k_split <- UMAP_split(LTR_kSNPs, HGDP, "HGDP - 1.000 SNPs in LTR TEs"))
(UMAP_LTR_1k <- UMAP(LTR_kSNPs, HGDP, "HGDP - 1.000 SNPs in LTR TEs"))

(UMAP_LTR_10k_split <- UMAP_split(LTR_k10SNPs, HGDP, "HGDP - 10.000 SNPs in LTR TEs"))
(UMAP_LTR_10k <- UMAP(LTR_k10SNPs, HGDP, "HGDP - 10.000 SNPs in LTR TEs"))
```
