---
title: "Archaic humans - SNPs found in NH and DH"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '/Users/rpianezza/TE/')
```

Set the environment and creating metadata file.
```{r}
library(tidyverse)
library(umap)

theme_set(theme_bw())

HGDP <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv") %>% select(ID, sex, country, pop) %>% distinct()

HGDP_afr_fem <- HGDP %>% filter(sex=="female", country=="Africa") %>% select(ID) %>% distinct()
HGDP_fem <- HGDP %>% filter(sex=="female") %>% select(ID, pop, country) %>% distinct()

coordinates <- read_tsv("/Users/rpianezza/TE/summary-HGDP/HGDP_populationcoordinates.txt", col_names = c("pop", "region", "latitude", "longitude")) %>% select(pop, latitude, longitude)

#write_tsv(HGDP_afr_fem, file="/Volumes/Temp1/rpianezza/archaic-introgression/ID-afr-females.txt")
```

```{r}
HGDP_full <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv")
a_HGDP <- read_tsv("/Volumes/Temp1/rpianezza/PCA-copynumber-all-analysis/a_HGDP.tsv")
HGDP_nobiased_samples <- filter(a_HGDP, (a > (-0.5)) & (a<0.5)) %>% select(ID) %>% pull()
HGDP_clean <- filter(HGDP_full, ID %in% HGDP_nobiased_samples, sex=="female") %>% group_by(familyname) %>% summarise(mean_cn = mean(copynumber)) %>% mutate(familyname = paste0(familyname, "_te"))

#write_tsv(HGDP_clean, file = "/Volumes/Temp1/rpianezza/archaic-introgression/female-copynumber.tsv")
```

## TEs

Base order: A T C G

```{r scg-matrixes}
vindija <- "/Volumes/Temp1/rpianezza/archaic-introgression/output/vindija.tsv"
altai <- "/Volumes/Temp1/rpianezza/archaic-introgression/output/test/altai.tsv"
denisova <- "/Volumes/Temp1/rpianezza/archaic-introgression/output/test/denisovan.tsv"
```

```{r function}
plot_introgression <- function(data, titlee){
  
 plot <- data %>% group_by(pop, country) %>% dplyr::summarise(mean_intro = mean(introgressed), sd_intro = sd(introgressed)) %>% ggplot(aes(x = reorder(pop, -mean_intro), y=mean_intro, fill=country))+
  geom_col()+
  geom_errorbar(aes(ymin = mean_intro - sd_intro, ymax = mean_intro + sd_intro), 
                width = 0.2, position = position_dodge(0.9), alpha = 0.5)+
  labs(x = "", y = "Introgressed variants", title = element_text(face = "bold", size = 14, titlee)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), legend.position = "bottom", plot.title = element_text(hjust = 0.5))
}


plot_map <- function(intro, coord, title){
  
full <- inner_join(intro, coord, by="pop") %>% group_by(pop, longitude, latitude) %>% dplyr::summarise(introgressed = mean(introgressed), count = n())
world_map = map_data("world")

ggplot() +
  geom_map(
    data = world_map, map = world_map,
    aes(long, lat, map_id = region),
    color = "white", fill = "lightgray", size = 0) +
  geom_point(data = full, aes(x=longitude, y=latitude, color = introgressed, size = count)) + geom_errorbar() + scale_colour_gradient(low = "green", high = "red") + theme(legend.position="top") + theme(plot.title = element_text(hjust = 0.5)) + ggtitle(title) + labs(colour = "Introgressed variants", size = "Samples")
}
```

```{r}
d <- read_tsv(denisova) %>% inner_join(HGDP_clean, by="familyname") %>% mutate(SNP = paste0(familyname, "_", position)) %>% select(-familyname, -position) %>% relocate(mean_cn) %>% relocate(SNP)
v <- read_tsv(vindija) %>% inner_join(HGDP_clean, by="familyname") %>% mutate(SNP = paste0(familyname, "_", position)) %>% select(-familyname, -position) %>% relocate(mean_cn) %>% relocate(SNP)
a <- read_tsv(altai) %>% inner_join(HGDP_clean, by="familyname") %>% mutate(SNP = paste0(familyname, "_", position)) %>% select(-familyname, -position) %>% relocate(mean_cn) %>% relocate(SNP)

specific_v <- v %>% filter(!(SNP %in% a$SNP))
two_n <- bind_rows(a, specific_v)

(specific_d <- d %>% filter(!(SNP %in% two_n$SNP)))
(specific_n <- two_n %>% filter(!(SNP %in% d$SNP)))
```

```{r}
n_variants <- specific_n %>% mutate_at(vars(starts_with("HGDP")), ~. * mean_cn) %>% filter(mean_cn<10000) %>% select(-c(diagnostic, mean_cn, SNP)) %>% dplyr::summarise_all(~sum(. >1, na.rm=TRUE)) %>% t %>% as.data.frame() %>% rownames_to_column(var = "ID") %>% as_tibble() %>% dplyr::rename("introgressed" = "V1") %>% separate(ID, into=c("ID", "pop"), sep="-", remove=FALSE) %>% select(-pop) %>% inner_join(HGDP_fem, by="ID")

(bar <- plot_introgression(n_variants, "Neandertal (RepSeq)"))
(mappa <- plot_map(n_variants, coordinates, "Neandertal (RepSeq)"))
```

```{r}
(d_variants <- specific_d %>% mutate_at(vars(starts_with("HGDP")), ~. * mean_cn) %>% filter(mean_cn<100) %>% select(-c(diagnostic, mean_cn, SNP)) %>% dplyr::summarise_all(~sum(. >1, na.rm=TRUE)) %>% t %>% as.data.frame() %>% rownames_to_column(var = "ID") %>% as_tibble() %>% dplyr::rename("introgressed" = "V1") %>% separate(ID, into=c("ID", "pop"), sep="-", remove=FALSE) %>% select(-pop) %>% inner_join(HGDP_fem, by="ID"))

(bar <- plot_introgression(d_variants, "Denisovan (RepSeq)"))
(mappa <- plot_map(d_variants, coordinates, "Denisovan (RepSeq)"))
```

```{r}
DNA_names <- c("Crypton", "hAT", "Helitron", "Kolobok", "Mariner/Tc1", "Merlin", "MuDR", "piggyBac", "DNA transposon")
LINE_names <- c("L1", "CR1", "L2", "Crack", "RTE", "RTEX", "R4", "Vingi", "Tx1", "Penelope")
SINE_names <- c("SINE1/7SL", "SINE2/tRNA", "SINE3/5S", "SINE")
LTR_names <- c("ERV1", "ERV2", "ERV3", "Gypsy", "Endogenous Retrovirus", "LTR Retrotransposon", "Long terminal repeat", "Non-LTR Retrotransposon")
satellites_names <- c("Satellite", "satellite", "SAT")

classification <- HGDP_full %>% filter(type=="te") %>% mutate(class = case_when(superfamily %in% DNA_names ~ "DNA", superfamily %in% LINE_names ~ "LINE", superfamily %in% SINE_names ~ "SINE", superfamily %in% LTR_names ~ "LTR", superfamily %in% satellites_names ~ "satellite"))

class <- classification %>% select(familyname, class, length) %>% distinct() %>% group_by(class) %>% summarise(families = n())
  
(bases <- classification %>% filter(sex=="female") %>% group_by(familyname, class, length) %>% summarise(copynumber = mean(copynumber)) %>% group_by(class) %>% summarise(bases = sum(length)) %>% inner_join(class,  by="class"))
```

```{r}
pies <- function(data, class_bases){
  
count <- data %>% mutate_at(vars(starts_with("HGDP")), ~. * mean_cn) %>% filter(mean_cn<10000) %>% select(-mean_cn) %>% mutate(variants = rowSums(. > 1)) %>% select(SNP, variants) %>% separate(SNP, into=c("familyname","position"), sep="_te_")
  
(c <- classification %>% select(familyname, class, length) %>% distinct() %>% inner_join(count, by="familyname"))
  
introgressed_class <- c %>%
  group_by(class) %>%
  summarise(variants = sum(variants, na.rm = TRUE))

pie_tib <- introgressed_class %>% inner_join(class_bases, by="class") %>% mutate(var_per_base = variants/bases)


pie <- ggplot(pie_tib, aes(x="", y=variants, fill=class))+
  geom_col(width = 1) + labs(fill='') +
  coord_polar(theta="y", start = pi/2)+
  theme_void()+
  geom_text(aes(label = ifelse(variants>50, variants, "")), 
            position = position_stack(vjust = 0.5), 
            size = 4)+
  theme(legend.position = "left")+
 scale_fill_manual(values=c("#F8766D", "#7CAE00", "#00BFC4", "#C77CFF", "#D89000"))

pie_norm <- ggplot(pie_tib, aes(x="", y=var_per_base, fill=class))+
  geom_col(width = 1) + labs(fill='') +
  coord_polar(theta="y", start = pi/2)+
  theme_void()+
  geom_text(aes(label = class), 
            position = position_stack(vjust = 0.5), 
            size = 4)+
  theme(legend.position = "none")+
 scale_fill_manual(values=c("#F8766D", "#7CAE00", "#00BFC4", "#C77CFF", "#D89000"))

list(raw = pie, introgressed_per_position = pie_norm)
}
```


```{r}
d_class <- pies(specific_d, bases)
d_class$raw
d_introgressed_per_site <- d_class$introgressed_per_position

n_class <- pies(specific_n, bases)
n_class$raw
n_introgressed_per_site <- n_class$introgressed_per_position
```

```{r}
ggsave(n_introgressed_per_site, file="/Volumes/Temp1/rpianezza/paper/figures-v2.0/ai/NH-introgressed-per-site.png", dpi=1000)

ggsave(d_introgressed_per_site, file="/Volumes/Temp1/rpianezza/paper/figures-v2.0/ai/DH-introgressed-per-site.png", dpi=1000)
```