---
title: "UMAP - HGDP - SNPs - SCGs"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

## Prepare the environment

```{r env}
library(tidyverse)
library(ggpubr)
library(umap)
```

## Select samples with no GC-bias

```{r samples selection}
HGDP <- read_delim("/Volumes/Temp1/rpianezza/0.old/summary-HGDP/HGDP_cutoff_classified.tsv")

HGDP_pcr_free_samples <- read_tsv("/Volumes/Temp1/rpianezza/investigation/HGDP-no-PCR/HGDP-only-pcr-free-samples.tsv", col_names = "ID")
HGDP_pcr_free <- HGDP %>% filter(ID %in% HGDP_pcr_free_samples$ID)

a_HGDP <- read_tsv("/Volumes/Temp1/rpianezza/PCA-copynumber-all-analysis/a_HGDP.tsv")
HGDP_nobiased_samples <- filter(a_HGDP, (a>(-0.5)) & (a<0.5)) %>% select(ID) %>% pull()
HGDP_final <- filter(HGDP_pcr_free, ID %in% HGDP_nobiased_samples)
```

## Read the SNPs matrixes

The SNPs matrixes are created using the script **frequency_matrix_scgs.py**.

```{r SNP-matrixes}
cov15_var01247 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.cov15.var01247.frequency.matrix.tsv_processed"
cov15_var008 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.cov15.var008.frequency.matrix.tsv_processed"
cov7_var01247 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.cov7.var01247.frequency.matrix.tsv_processed"
cov7_var008 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.cov7.var008.frequency.matrix.tsv_processed"
cov15_var002 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.cov15.var002.frequency.matrix.tsv_processed"
cov15_var001 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.cov15.var001.frequency.matrix.tsv_processed"
nogc_cov15_var01219 <- "/Volumes/Temp1/rpianezza/PCA-SNPs-all-analysis/scgs/scg.nogcbias-cov15.var01219.frequency.matrix.tsv_processed"
```

## Create the function for UMAP plotting

```{r main-function}
UMAP <- function(freq_matrix, metadata, titlee){

matrix <- read_csv(freq_matrix)
metadata <- metadata %>% select(ID, sex, country, pop) %>% distinct()
matrix <- inner_join(metadata, matrix, by="ID")

pca_data <- matrix %>% select_if(~ !all(. == .[1]))
matrix <- as.matrix(pca_data[, -c(1,2,3,4)])

umap_result <- umap(matrix, n_neighbors = 15, min_dist = 0.3)

umap <- umap_result$layout %>% as.data.frame() %>% rename(UMAP1="V1",UMAP2="V2")

plot <- umap %>% ggplot(aes(x = UMAP1, y = UMAP2, color = metadata$country))+
  geom_point()+ labs(x = "UMAP1", y = "UMAP2", title = titlee, color = "Region") + theme(plot.title = element_text(hjust = 0.5), legend.title = element_text(face = "bold"))
}
```


```{r}
(UMAP_cov15_var01247 <- UMAP(cov15_var01247, HGDP, "SNPs - SCGs - Cov 15 - Var 0.1247"))
```

```{r}
(UMAP_cov15_var008 <- UMAP(cov15_var008, HGDP, "SNPs - SCGs - Cov 15 - Var 0.008"))
```

```{r}
(UMAP_cov7_var01247 <- UMAP(cov7_var01247, HGDP, "SNPs - SCGs - Cov 7 - Var 0.1247"))
```

```{r}
(UMAP_cov7_var008 <- UMAP(cov7_var008, HGDP, "SNPs - SCGs - Cov 7 - Var 0.008"))
```

```{r}
(UMAP_cov15_var002 <- UMAP(cov15_var002, HGDP, "SNPs - SCGs - Cov 15 - Var 0.002"))
```

```{r}
(UMAP_cov15_var001 <- UMAP(cov15_var001, HGDP, "SNPs - SCGs - Cov 15 - Var 0.001"))
```


