---
title: "SNPs - GC filtered"
output: rmarkdown::github_document
editor_options: 
  markdown: 
    wrap: sentence
---

## Prepare the environment

```{r env}
library(tidyverse)
library(ggpubr)
```

## Read the summary files

```{r summary-files}
HGDP<-read_delim("/Volumes/Temp1/rpianezza/TE/summary-HGDP/USEME_HGDP_complete_reflib6.2_mq10_batchinfo_cutoff0.01.txt")
names(HGDP)<-c("ID","pop","sex","country","type","familyname","length","reads","copynumber","batch")

SGDP <- read_tsv("/Volumes/Temp2/rpianezza/SGDP/summary/USEME_SGDP_cutoff") %>% dplyr::rename(ID=biosample)

HGDP_pcr_free_samples <- read_tsv("/Volumes/Temp1/rpianezza/investigation/HGDP-no-PCR/HGDP-only-pcr-free-samples.tsv", col_names = "ID")
HGDP_pcr_free <- HGDP %>% filter(ID %in% HGDP_pcr_free_samples$ID)
HGDP_pcr <- HGDP %>% filter(!(ID %in% HGDP_pcr_free_samples$ID))

SGDP_pcr_free_samples <- read_tsv("/Volumes/Temp1/rpianezza/SGDP/ric-documentation/SGDP-no-PCR.tsv")
SGDP_pcr_free <- SGDP %>% filter(ID %in% SGDP_pcr_free_samples$ID)
SGDP_pcr <- SGDP %>% filter(!(ID %in% SGDP_pcr_free_samples$ID))
```

## Read the SNPs matrixes

The SNPs matrixes are created using the script **frequency_matrix_v2.py** with arguments **--max_freq 0.8 --min_cov 5000 --transv n**. The last argument make the script only considering SNPs which do not create transversions, to avoid GC-bias (only A-T or G-C SNPs are retained).

```{r SNP-matrixes}
HGDP_45_55 = "/Volumes/Temp1/rpianezza/SNPs-all-analysis/matrixes/HGDP.08.5000.45-55.matrix_processed"
SGDP_45_55 = "/Volumes/Temp1/rpianezza/SNPs-all-analysis/matrixes/SGDP.08.5000.45-55.matrix_processed"

HGDP_noGCbias_45_55 = "/Volumes/Temp1/rpianezza/SNPs-all-analysis/matrixes/HGDP.notransv.08.5000.45-55.matrix_processed"
SGDP_noGCbias_45_55 = "/Volumes/Temp1/rpianezza/SNPs-all-analysis/matrixes/SGDP.notransv.08.5000.45-55.matrix_processed"
```

## Create the function for PCA plotting

```{r main-function}
PCA <- function(freq_matrix, metadata, titlee){

matrix <- read_csv(freq_matrix)
  
f_metadata <- metadata %>% filter(sex=="female") %>% select(ID, sex, country, pop) %>% distinct()
m_metadata <- metadata %>% filter(sex=="male") %>% select(ID, sex, country, pop) %>% distinct()
males_matrix <- inner_join(m_metadata, matrix, by="ID")
females_matrix <- inner_join(f_metadata, matrix, by="ID")

f_pca_data <- females_matrix %>%  select_if(~ !all(. == .[1]))
m_pca_data <- males_matrix %>%  select_if(~ !all(. == .[1]))
f_pca_result <- prcomp(f_pca_data[, -c(1:3)], center = TRUE, scale = TRUE)
m_pca_result <- prcomp(m_pca_data[, -c(1:3)], center = TRUE, scale = TRUE)
      
f_var_explained <- f_pca_result$sdev^2/sum(f_pca_result$sdev^2)
m_var_explained <- m_pca_result$sdev^2/sum(m_pca_result$sdev^2)
      
f <- ggplot(data.frame(f_pca_result$x, country=females_matrix$country), aes(x=PC1,y=PC2, color=country)) + geom_point(size=2) + labs(x=paste0("PC1: ",round(f_var_explained[1]*100,1),"%"), y=paste0("PC2: ",round(f_var_explained[2]*100,1),"%")) + ggtitle("Females") + theme(plot.title = element_text(hjust = 0.5))
   
m <- ggplot(data.frame(m_pca_result$x, country=males_matrix$country), aes(x=PC1,y=PC2, color=country)) + geom_point(size=2) + labs(x=paste0("PC1: ",round(m_var_explained[1]*100,1),"%"), y=paste0("PC2: ",round(m_var_explained[2]*100,1),"%")) + ggtitle("Males") + theme(plot.title = element_text(hjust = 0.5)) 
     
plot <- ggarrange(f, m, ncol = 2, nrow = 1, common.legend = TRUE, legend = "bottom", align = "hv", font.label = list(size = 10, color = "black", face = "bold", family = NULL, position = "top"))
    
annotate_figure(plot, top = text_grob(titlee, face = "bold", size = 14))
}
```

```{r main-plots}
PCA(HGDP_45_55, HGDP, "HGDP - SNPs - GC range 45-55%")
PCA(SGDP_45_55, SGDP, "SGDP - SNPs - GC range 45-55%")
```

```{r pcr-free}
PCA(HGDP_45_55, HGDP_pcr_free, "HGDP noPCR - SNPs - GC range 45-55%")
PCA(SGDP_45_55, SGDP_pcr_free, "SGDP noPCR - SNPs - GC range 45-55%")
```

```{r pcr}
PCA(HGDP_45_55, HGDP_pcr, "HGDP PCR - SNPs - GC range 45-55%")
```

```{r main-plots - noGCbias}
PCA(HGDP_noGCbias_45_55, HGDP, "HGDP - SNPs noGCbias - GC range 45-55%")
PCA(SGDP_noGCbias_45_55, SGDP, "SGDP - SNPs noGCbias - GC range 45-55%")
```

```{r pcr-free - noGCbias}
PCA(HGDP_noGCbias_45_55, HGDP_pcr_free, "HGDP noPCR - SNPs noGCbias - GC range 45-55%")
PCA(SGDP_noGCbias_45_55, SGDP_pcr_free, "SGDP noPCR - SNPs noGCbias - GC range 45-55%")
```

```{r pcr - noGCbias}
PCA(HGDP_noGCbias_45_55, HGDP_pcr, "HGDP PCR - SNPs noGCbias - GC range 45-55%")
```
